<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Jakobi Signature Sate',
                'slug' => 'jakobi-signature-sate',
                'category' => 'Chef Jakobi Selection',
                'description' => 'The crown jewel of Mr. Jakobi\'s kitchen. Tender chunks of prime chicken thighs, marinated for 24 hours in a complex blend of 17 regional spices, slow-grilled over coconut husk charcoal, and finished with our secret aromatic peanut glaze.',
                'price' => 45000,
                'image' => 'https://images.unsplash.com/photo-1606471191009-63994c53433b?w=800&q=80',
                'preparation_time' => '20 - 25 Minutes',
                'regional_origin' => 'East Ngawi Highlands',
                'calories' => 640,
                'total_fat' => '32G',
                'protein' => '45G',
                'carbs' => '18G',
                'sodium' => '480MG',
                'ingredients' => ['Prime Free-Range Chicken Thighs', 'Cold-Pressed Coconut Milk', 'Hand-Roasted Peanuts', 'Organic Palm Sugar (Gula Jawa)', 'Aged Tamarind Pulp'],
                'allergens' => ['Peanuts', 'Soy'],
                'method' => 'Our process begins with a 24-hour marinade. We then hand-thread the meat onto bamboo skewers before grilling over open-flame coconut husks, which imparts a distinct smokiness. The satay is basted continuously with peanut oil and spices until reaching caramelized perfection.',
                'serving_suggestion' => 'Best enjoyed with compressed rice cakes (Lontong), fresh shallots, and sliced bird\'s eye chilies for an authentic Ngawi experience.',
                'rating' => 5.0,
                'review_count' => 128,
            ],
            [
                'name' => 'Rawon Hitam Ngawi',
                'slug' => 'rawon-hitam-ngawi',
                'category' => 'Traditional Heritage',
                'description' => 'A deeply aromatic black beef soup, simmered for 8 hours with keluak (black nut) paste, lemongrass, and galangal. This ancient Ngawi recipe produces a rich, dark broth with complex layers of earthy, nutty, and savory flavors.',
                'price' => 55000,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
                'preparation_time' => '30 - 40 Minutes',
                'regional_origin' => 'West Ngawi Valley',
                'calories' => 520,
                'total_fat' => '28G',
                'protein' => '38G',
                'carbs' => '22G',
                'sodium' => '560MG',
                'ingredients' => ['Premium Beef Shank', 'Keluak (Black Nut)', 'Fresh Lemongrass', 'Galangal Root', 'Bean Sprouts'],
                'allergens' => ['Tree Nuts'],
                'method' => 'The keluak nuts are soaked and processed over three days. Beef is slow-simmered in the black broth until fork-tender, developing an incredibly deep umami profile.',
                'serving_suggestion' => 'Served with steamed rice, salted duck egg, bean sprouts, and sambal paste on the side.',
                'rating' => 4.8,
                'review_count' => 96,
            ],
            [
                'name' => 'Pecel Madiun Spesial',
                'slug' => 'pecel-madiun-spesial',
                'category' => 'Vegetarian Delight',
                'description' => 'A vibrant vegetable salad dressed in a rich, spicy peanut sauce made from hand-ground roasted peanuts, kencur, and bird\'s eye chilies. Topped with crispy rempeyek crackers for that perfect crunch.',
                'price' => 30000,
                'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
                'preparation_time' => '10 - 15 Minutes',
                'regional_origin' => 'Ngawi Central Market',
                'calories' => 380,
                'total_fat' => '18G',
                'protein' => '14G',
                'carbs' => '42G',
                'sodium' => '320MG',
                'ingredients' => ['Fresh Morning Spinach', 'Long Beans', 'Bean Sprouts', 'Hand-Ground Peanut Sauce', 'Rempeyek Crackers'],
                'allergens' => ['Peanuts'],
                'method' => 'Vegetables are blanched to order, preserving their crunch and nutrients. The peanut sauce is freshly ground each morning using a traditional stone mortar.',
                'serving_suggestion' => 'Enjoy with warm steamed rice and a side of tempeh goreng for a complete meal.',
                'rating' => 4.9,
                'review_count' => 205,
            ],
            [
                'name' => 'Nasi Goreng Kambing',
                'slug' => 'nasi-goreng-kambing',
                'category' => 'Chef Jakobi Selection',
                'description' => 'Smoky fried rice wok-tossed with tender slices of marinated lamb, sweet soy glaze, shallots, and garlic. Crowned with a perfectly fried egg and served with acar pickles and kerupuk.',
                'price' => 50000,
                'image' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
                'preparation_time' => '15 - 20 Minutes',
                'regional_origin' => 'East Ngawi Highlands',
                'calories' => 720,
                'total_fat' => '35G',
                'protein' => '32G',
                'carbs' => '68G',
                'sodium' => '620MG',
                'ingredients' => ['Day-Old Jasmine Rice', 'Marinated Lamb Slices', 'Sweet Soy Sauce (Kecap Manis)', 'Free-Range Egg', 'Fresh Shallots & Garlic'],
                'allergens' => ['Soy', 'Egg'],
                'method' => 'Cooked in a blazing-hot wok for that authentic smoky wok-hei flavor. The lamb is pre-marinated in a blend of cumin, coriander, and sweet soy for 6 hours.',
                'serving_suggestion' => 'Best paired with a cold es jeruk (orange iced tea) and extra sambal on the side.',
                'rating' => 4.7,
                'review_count' => 87,
            ],
            [
                'name' => 'Es Dawet Ireng',
                'slug' => 'es-dawet-ireng',
                'category' => 'Festival Beverages',
                'description' => 'A refreshing traditional black cendol drink made with charcoal-infused rice flour jelly, creamy coconut milk, and organic palm sugar syrup. The perfect cool-down after exploring the festival.',
                'price' => 18000,
                'image' => 'https://images.unsplash.com/photo-1532634896-26909d0d4b89?w=800&q=80',
                'preparation_time' => '5 - 8 Minutes',
                'regional_origin' => 'Ngawi River District',
                'calories' => 280,
                'total_fat' => '12G',
                'protein' => '4G',
                'carbs' => '38G',
                'sodium' => '45MG',
                'ingredients' => ['Charcoal Rice Flour Jelly', 'Fresh Coconut Milk', 'Organic Palm Sugar Syrup', 'Pandan Leaves', 'Shaved Ice'],
                'allergens' => [],
                'method' => 'The cendol jelly is hand-pressed through a traditional sieve, creating perfectly shaped droplets. Palm sugar is slow-cooked into a rich caramel syrup.',
                'serving_suggestion' => 'Served ice-cold in a traditional clay cup for the full heritage experience.',
                'rating' => 4.6,
                'review_count' => 153,
            ],
            [
                'name' => 'Tahu Tek Ngawi',
                'slug' => 'tahu-tek-ngawi',
                'category' => 'Street Food Classics',
                'description' => 'Crispy fried tofu and lontong rice cakes smothered in a savory-sweet petis (shrimp paste) sauce, topped with crunchy kerupuk, fresh bean sprouts, and a drizzle of sweet soy.',
                'price' => 25000,
                'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
                'preparation_time' => '10 - 12 Minutes',
                'regional_origin' => 'Ngawi Town Square',
                'calories' => 420,
                'total_fat' => '22G',
                'protein' => '18G',
                'carbs' => '35G',
                'sodium' => '510MG',
                'ingredients' => ['Firm Tofu (Fried Crispy)', 'Compressed Rice Cake (Lontong)', 'Petis Shrimp Paste Sauce', 'Kerupuk Crackers', 'Fresh Bean Sprouts'],
                'allergens' => ['Soy', 'Shellfish'],
                'method' => 'Tofu is double-fried for maximum crispiness. The petis sauce is a closely guarded family recipe, blending shrimp paste with palm sugar and tamarind.',
                'serving_suggestion' => 'Enjoy immediately while the tofu is still crispy. Add extra chili sauce for a spicy kick.',
                'rating' => 4.5,
                'review_count' => 74,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
